
const CATS=['All Games','Action','Adventure','Arcade','Racing','Sports','Puzzle','Shooting','2 Player','.io','Strategy','Hypercasual','Soccer'];
const ICONS=['⌂','⚔','◇','✦','⌁','⚽','✣','⚔','♙','✧','♜','●','⚽'];
let games=[];const qs=new URLSearchParams(location.search),catParam=qs.get('category')||'All Games',page=Math.max(1,parseInt(qs.get('page')||'1')||1),perPage=24;
fetch('games.json').then(r=>r.json()).then(g=>{games=g;init()});
const norm=s=>String(s||'').toLowerCase(),esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function filtered(){let a=games.filter(g=>g.title&&g.thumb&&g.url);if(catParam!=='All Games')a=a.filter(g=>norm(g.category).includes(norm(catParam))||norm(g.tags).includes(norm(catParam)));let seed=page*9301+catParam.length*97;for(let i=a.length-1;i>0;i--){let x=Math.sin(seed+i*12.9898)*43758.5453,j=Math.floor((x-Math.floor(x))*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function card(g){return `<a class="card" href="game.html?id=${encodeURIComponent(g.id)}" title="${esc(g.title)}"><img loading="lazy" src="${esc(g.thumb)}" alt="${esc(g.title)}"><span class="cardTitle">${esc(g.title)}</span><span class="orbit"></span></a>`}
function init(){let grid=document.querySelector('#gameGrid');if(!grid)return;let a=filtered(),total=Math.ceil(a.length/perPage),start=(page-1)*perPage;document.querySelector('#gameCount').textContent=games.length.toLocaleString();document.querySelector('#pageCount').textContent=page+' / '+total;let h='';a.slice(start,start+perPage).forEach((g,i)=>{h+=card(g);if(i===5)h+='<div class="ad-wrap"><div class="ad-slot" data-banner-id="1499097"></div></div>';if(i===13)h+='<div class="ad-wrap"><div class="ad-slot" data-banner-id="1499084"></div></div>'});grid.innerHTML=h;document.querySelector('#pagination').innerHTML=pages(total);document.querySelector('#categoryLabel').textContent=catParam;buildCats();let s=document.querySelector('#search');if(s)s.oninput=e=>filterSearch(e.target.value)}
function filterSearch(q){let g=document.querySelector('#gameGrid');if(!g)return;g.innerHTML=games.filter(x=>norm(x.title).includes(norm(q))).slice(0,48).map(card).join('')}
function pages(total){let max=Math.min(total,869),set=new Set([1,page,Math.max(1,page-1),Math.min(max,page+1),max]),o='';[...set].sort((a,b)=>a-b).forEach(n=>o+=`<a class="page ${n===page?'active':''}" href="?page=${n}${catParam!=='All Games'?'&category='+encodeURIComponent(catParam):''}">${n}</a>`);return o}
function buildCats(){let e=document.querySelector('#cats');if(e)e.innerHTML=CATS.map((c,i)=>`<a class="cat ${c===catParam?'active':''}" href="?category=${encodeURIComponent(c)}"><span class="ico">${ICONS[i]}</span><span>${c}</span></a>`).join('')}
